ChargeBackCalculation-master/ChargeBackCalculation/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ChargeBackCalculation.Models
{
    public class Employee
    {
        public int Id { get; set; }
        [Display(Name = "Customer Id")]
        public int CustomerId { get; set; }

        [Required(ErrorMessage = " Account no is Required")]
        [StringLength(11)]
        public string BankAccountNumber { get; set; }

        [Required(ErrorMessage = " Bank Branch is Required")]
        public string BankBranchName { get; set; }
        [Required(ErrorMessage = "Enter Address")]

        public string BankAddress { get; set; }
        public int AvailableBalance { get; set; }
    }
}

ChargeBackCalculation-master/ChargeBackCalculation/Controllers/ComplaintRegistersController.cs
using ChargeBackCalculation.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ChargeBackCalculation.Controllers
{
    public class ComplaintRegistersController : Controller
    {
        private UserLoginDbContext db = new UserLoginDbContext();
        // GET: ComplaintRegisters
        public ActionResult Index()
        {
            return View(db.ComplaintRegisters.ToList());
        }
        public ActionResult Index1()
        {
            return View();
        }
        // complaint registration for the customer
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,FirstName,LastName,PhoneNumber,Email,BankAccountNo,BankBranch,ChargeBackAmount,Reason,DateOfTransaction")] ComplaintRegister complaintregister, int customerid)
        {
            if (ModelState.IsValid)
            {

                var user = db.CustomerRegisters.Where(x => x.UserId == customerid).FirstOrDefault();
                if (user != null)
                {
                    var user1 = db.Employees.Where(x => x.CustomerId == customerid).FirstOrDefault();
                    if (user1 != null)
                    {
                        db.ComplaintRegisters.Add(complaintregister);
                        db.SaveChanges();
                        TempData["Message"] = "Complaint Lodged Successfully ";
                        return View();
                    }
                    else
                    {
                        return View(complaintregister);
                    }
                }
            }

            return View(complaintregister);
        }
    }
}

ChargeBackCalculation-master/ChargeBackCalculation/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ChargeBackCalculation.Models;

namespace ChargeBackCalculation.Controllers
{
    public class EmployeesController : Controller
    {
        private UserLoginDbContext db = new UserLoginDbContext();

        // GET: Employees
        //Display Customer Information along with search functionality
        [HttpGet]
        public ActionResult Index(string option, string search)
        {
            if (option == "BankAccountNumber")
            {
                return View(db.Employees.Where(x => x.BankAccountNumber == search || search == null).ToList());
            }
            else
            {
                return View(db.Employees.Where(x => x.BankAccountNumber.StartsWith(search) || search == null).ToList());
            }
            return View(db.Employees.ToList());
        }

        // GET: Employees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // GET: Employees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CustomerId,BankAccountNumber,BankBranchName,BankAddress,AvailableBalance")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(employee);
        }

        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CustomerId,BankAccountNumber,BankBranchName,BankAddress,AvailableBalance")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Employee employee = db.Employees.Find(id);
            if (employee == null)
            {
                return HttpNotFound();
            }
            return View(employee);
        }

        // POST: Employees/Delete/5
        // Confirmation For deleting
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Employee employee = db.Employees.Find(id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ChargeBackCalculation-master/ChargeBackCalculation/Views/Employees/Create.cshtml
@model ChargeBackCalculation.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankBranchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankBranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankBranchName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AvailableBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ChargeBackCalculation-master/ChargeBackCalculation/Views/Employees/Delete.cshtml
@model ChargeBackCalculation.Models.Employee

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankBranchName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankBranchName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableBalance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ChargeBackCalculation-master/ChargeBackCalculation/Views/Employees/Details.cshtml
@model ChargeBackCalculation.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Employee</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAccountNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankBranchName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankBranchName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AvailableBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AvailableBalance)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ChargeBackCalculation-master/ChargeBackCalculation/Views/Employees/Edit.cshtml
@model ChargeBackCalculation.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employee</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAccountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAccountNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAccountNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankBranchName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankBranchName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankBranchName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BankAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BankAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BankAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableBalance, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AvailableBalance, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AvailableBalance, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ChargeBackCalculation-master/ChargeBackCalculation/Views/Employees/Index.cshtml
@model IEnumerable<ChargeBackCalculation.Models.Employee>

@{ ViewBag.Title = "Index"; }

<h2>Index</h2>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("ChargeBack Calculator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("About", "About", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("Logout", "Index", "Home")</li>
            </ul>
        </div>
    </div>
</div>

@Html.ActionLink("ChargeBackDetails", "Index", "ComplaintRegisters")
@using (Html.BeginForm("Index", "Employees", FormMethod.Get))
{
    <text>BankAccountNumber:</text> @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CustomerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAccountNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankBranchName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BankAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AvailableBalance)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.CustomerId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BankAccountNumber)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BankBranchName)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.BankAddress)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.AvailableBalance)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Details", "Details", new { id = item.Id }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.Id })
    </td>
</tr>}

</table>